development:
  adapter: postgresql
  encoding: unicode
  database: WednesdayShelf_development
  pool: 5
  username: WednesdayShelf
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: WednesdayShelf_test
  pool: 5
  username: WednesdayShelf
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: WednesdayShelf_production
  pool: 5
  username: WednesdayShelf
  password:
